import { ThemeOptions } from '@/types'

const themeOptions: ThemeOptions = {
  light: {
    name: 'Light',
    bg: {
      main: 'bg-white',
      header: 'bg-gray-50',
      primary: 'bg-cyan-400',
      card: 'bg-white',
      panel: 'bg-gray-100',
      progress: 'bg-gray-100',
    },
    text: {
      main: 'text-gray-900',
      primary: 'text-cyan-400',
      subText: 'text-gray-500',
      link: 'text-gray-500',
      hoverPrimary: 'hover:text-cyan-400',
    },
    borders: {
      primary: 'border-cyan-400',
      text: 'border-gray-900',
      card: 'border-white',
      skeleton: 'border-cyan-100',
      hoverPrimary: 'hover:border-cyan-400',
      focusPrimary: 'focus:border-cyan-400',
    },
    rings: {
      bg: 'ring-white',
      header: 'ring-gray-50',
      primary: 'ring-cyan-400',
      focusPrimary: 'focus:ring-cyan-400',
    },
    skeletons: {
      main: 'bg-gray-300',
      second: 'bg-gray-500',
    },
    buttons: {
      primary: {
        bg: 'bg-cyan-400',
        text: 'text-cyan-900',
        hoverBg: 'hover:bg-cyan-500',
        hoverText: 'hover:text-cyan-900',
        focusBg: 'focus:bg-cyan-500',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-gray-900',
        border: 'text-gray-900',
        hoverBg: 'hover:bg-gray-900',
        hoverText: 'hover:text-white',
        focusBg: 'focus:bg-gray-900',
        focusText: 'focus:text-white',
      },
      self: {
        bg: 'bg-white',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-100',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-gray-100',
      placeholder: 'placeholder-gray-800',
    },
    gradients: {
      main: {
        from: 'from-cyan-400',
        to: 'to-cyan-200',
        direction: 'bg-gradient-to-tr',
      },
      bg: {
        from: 'from-blue-200',
        to: 'to-cyan-300',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-white',
        to: 'to-transparent',
      },

      button: {
        from: 'from-blue-300',
        to: 'to-cyan-400',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'hover:bg-gradient-to-tl',
        hoverFrom: 'hover:from-blue-400',
        hoverTo: 'hover:to-cyan-500',
        text: 'text-gray-800',
      },
      buttonTransition: {
        from: 'from-blue-300',
        to: 'to-cyan-400',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'bg-gradient-to-tl',
        hoverFrom: 'from-blue-400',
        hoverTo: 'to-cyan-500',
        text: 'text-gray-800',
      },
    },
  },
  dark: {
    name: 'Dark',
    bg: {
      main: 'bg-gray-900',
      header: 'bg-gray-800',
      primary: 'bg-cyan-400',
      card: 'bg-gray-700',
      panel: 'bg-gray-700',
      progress: 'bg-gray-800',
    },
    text: {
      main: 'text-gray-50',
      primary: 'text-cyan-400',
      subText: 'text-gray-200',
      link: 'text-gray-200',
      hoverPrimary: 'hover:text-cyan-400',
    },
    borders: {
      primary: 'border-cyan-400',
      text: 'border-gray-50',
      card: 'border-gray-700',
      skeleton: 'border-cyan-100',
      hoverPrimary: 'hover:border-cyan-400',
      focusPrimary: 'focus:border-cyan-400',
    },
    rings: {
      bg: 'ring-gray-900',
      header: 'ring-gray-800',
      primary: 'ring-cyan-400',
      focusPrimary: 'focus:ring-cyan-400',
    },
    skeletons: {
      main: 'bg-gray-500',
      second: 'bg-gray-800',
    },
    buttons: {
      primary: {
        bg: 'bg-cyan-400',
        text: 'text-cyan-900',
        hoverBg: 'hover:bg-cyan-500',
        hoverText: 'hover:text-cyan-900',
        focusBg: 'focus:bg-cyan-500',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-gray-50',
        border: 'text-gray-50',
        hoverBg: 'hover:bg-gray-50',
        hoverText: 'hover:text-gray-900',
        focusBg: 'focus:bg-gray-50',
        focusText: 'focus:text-gray-900',
      },
      self: {
        bg: 'bg-gray-900',
        text: 'text-gray-50',
        hoverBg: 'hover:bg-gray-700',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-gray-800',
      placeholder: 'placeholder-gray-100',
    },
    gradients: {
      main: {
        from: 'from-cyan-300',
        to: 'to-cyan-100',
        direction: 'bg-gradient-to-tr',
      },
      bg: {
        from: 'from-cyan-200',
        to: 'to-cyan-500',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-gray-900',
        to: 'to-transparent',
      },
      button: {
        from: 'from-cyan-500',
        to: 'to-teal-400',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'hover:bg-gradient-to-tl',
        hoverFrom: 'hover:from-cyan-600',
        hoverTo: 'hover:to-teal-500',
        text: 'text-gray-900',
      },
      buttonTransition: {
        from: 'from-cyan-500',
        to: 'to-teal-400',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'bg-gradient-to-tl',
        hoverFrom: 'from-cyan-600',
        hoverTo: 'to-teal-500',
        text: 'text-gray-900',
      },
    },
  },
  blue: {
    name: 'Blue',
    bg: {
      main: 'bg-blue-900',
      header: 'bg-blue-800',
      primary: 'bg-orange-400',
      card: 'bg-blue-600',
      panel: 'bg-blue-600',
      progress: 'bg-blue-800',
    },
    text: {
      main: 'text-blue-50',
      primary: 'text-orange-400',
      subText: 'text-blue-300',
      link: 'text-blue-100',
      hoverPrimary: 'hover:text-orange-400',
    },
    borders: {
      primary: 'border-orange-400',
      text: 'border-blue-50',
      card: 'border-blue-600',
      skeleton: 'border-orange-100',
      hoverPrimary: 'hover:border-orange-400',
      focusPrimary: 'focus:border-orange-400',
    },
    rings: {
      bg: 'ring-blue-900',
      header: 'ring-blue-800',
      primary: 'ring-orange-400',
      focusPrimary: 'focus:ring-orange-400',
    },
    skeletons: {
      main: 'bg-blue-500',
      second: 'bg-blue-800',
    },
    buttons: {
      primary: {
        bg: 'bg-orange-400',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-orange-500',
        hoverText: 'hover:text-gray-900',
        focusBg: 'focus:bg-orange-500',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-blue-50',
        border: 'text-blue-50',
        hoverBg: 'hover:bg-blue-50',
        hoverText: 'hover:text-blue-900',
        focusBg: 'focus:bg-blue-50',
        focusText: 'focus:text-blue-900',
      },
      self: {
        bg: 'bg-blue-500',
        text: 'text-blue-50',
        hoverBg: 'hover:bg-blue-600',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-blue-700',
      placeholder: 'placeholder-blue-100',
    },
    gradients: {
      main: {
        from: 'from-orange-300',
        to: 'to-orange-200',
        direction: 'bg-gradient-to-tr',
      },
      bg: {
        from: 'from-blue-200',
        to: 'to-blue-500',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-blue-900',
        to: 'to-transparent',
      },
      button: {
        from: 'from-yellow-400',
        to: 'to-orange-300',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'hover:bg-gradient-to-tl',
        hoverFrom: 'hover:from-yellow-400',
        hoverTo: 'hover:to-orange-400',
        text: 'text-yellow-900',
      },
      buttonTransition: {
        from: 'from-yellow-400',
        to: 'to-orange-300',
        direction: 'bg-gradient-to-tr',
        hoverDirection: 'bg-gradient-to-tl',
        hoverFrom: 'from-yellow-400',
        hoverTo: 'to-orange-400',
        text: 'text-yellow-900',
      },
    },
  },
  indigo: {
    name: 'Indigo',
    bg: {
      main: 'bg-indigo-900',
      header: 'bg-indigo-800',
      primary: 'bg-lime-600',
      card: 'bg-indigo-600',
      panel: 'bg-indigo-600',
      progress: 'bg-indigo-800',
    },
    text: {
      main: 'text-indigo-50',
      primary: 'text-lime-600',
      subText: 'text-indigo-300',
      link: 'text-indigo-100',
      hoverPrimary: 'hover:text-lime-600',
    },
    borders: {
      primary: 'border-lime-600',
      text: 'border-indigo-50',
      card: 'border-indigo-600',
      skeleton: 'border-lime-100',
      hoverPrimary: 'hover:border-lime-600',
      focusPrimary: 'focus:border-lime-600',
    },
    rings: {
      bg: 'ring-indigo-900',
      header: 'ring-indigo-800',
      primary: 'ring-lime-600',
      focusPrimary: 'focus:ring-lime-600',
    },
    skeletons: {
      main: 'bg-indigo-500',
      second: 'bg-indigo-800',
    },
    buttons: {
      primary: {
        bg: 'bg-lime-500',
        text: 'text-indigo-900',
        hoverBg: 'hover:bg-lime-600',
        hoverText: 'hover:text-indigo-900',
        focusBg: 'focus:bg-lime-600',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-indigo-50',
        border: 'text-indigo-50',
        hoverBg: 'hover:bg-indigo-50',
        hoverText: 'hover:text-indigo-900',
        focusBg: 'focus:bg-indigo-50',
        focusText: 'focus:text-indigo-900',
      },
      self: {
        bg: 'bg-indigo-500',
        text: 'text-indigo-50',
        hoverBg: 'hover:bg-indigo-600',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-indigo-700',
      placeholder: 'placeholder-indigo-100',
    },
    gradients: {
      main: {
        from: 'from-lime-300',
        to: 'to-lime-50',
        direction: 'bg-gradient-to-tr',
        text: 'text-lime-900',
      },
      bg: {
        from: 'from-indigo-200',
        to: 'to-indigo-500',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-indigo-900',
        to: 'to-transparent',
      },
      button: {
        from: 'from-lime-500',
        to: 'to-lime-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'hover:bg-gradient-to-tr',
        hoverFrom: 'hover:from-lime-600',
        hoverTo: 'hover:to-lime-200',
        text: 'text-lime-900',
      },
      buttonTransition: {
        from: 'from-lime-500',
        to: 'to-lime-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'bg-gradient-to-tr',
        hoverFrom: 'from-lime-600',
        hoverTo: 'to-lime-200',
        text: 'text-lime-900',
      },
    },
  },
  rose: {
    name: 'Rose',
    bg: {
      main: 'bg-rose-200',
      header: 'bg-rose-50',
      primary: 'bg-red-700',
      card: 'bg-rose-100',
      panel: 'bg-rose-100',
      progress: 'bg-rose-200',
    },
    text: {
      main: 'text-rose-900',
      primary: 'text-red-700',
      subText: 'text-rose-700',
      link: 'text-red-700',
      hoverPrimary: 'hover:text-red-700',
    },
    borders: {
      primary: 'border-red-700',
      text: 'border-rose-900',
      card: 'border-rose-100',
      skeleton: 'border-red-100',
      hoverPrimary: 'hover:border-red-700',
      focusPrimary: 'focus:border-red-700',
    },
    rings: {
      bg: 'ring-rose-200',
      header: 'ring-rose-50',
      primary: 'ring-red-700',
      focusPrimary: 'focus:ring-red-700',
    },
    skeletons: {
      main: 'bg-rose-300',
      second: 'bg-rose-400',
    },
    buttons: {
      primary: {
        bg: 'bg-red-700',
        text: 'text-white',
        hoverBg: 'hover:bg-red-800',
        hoverText: 'hover:text-white',
        focusBg: 'focus:bg-red-800',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-rose-900',
        border: 'text-rose-900',
        hoverBg: 'hover:bg-rose-900',
        hoverText: 'hover:text-rose-200',
        focusBg: 'focus:bg-rose-900',
        focusText: 'focus:text-rose-200',
      },
      self: {
        bg: 'bg-rose-50',
        text: 'text-rose-900',
        hoverBg: 'hover:bg-rose-100',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-rose-300',
      placeholder: 'placeholder-rose-700',
    },
    gradients: {
      main: {
        from: 'from-red-300',
        to: 'to-red-100',
        direction: 'bg-gradient-to-tr',
        text: 'text-red-900',
      },
      bg: {
        from: 'from-red-200',
        to: 'to-red-300',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-rose-200',
        to: 'to-transparent',
      },
      button: {
        from: 'from-red-100',
        to: 'to-red-300',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'hover:bg-gradient-to-tr',
        hoverFrom: 'hover:from-red-200',
        hoverTo: 'hover:to-red-400',
        text: 'text-red-900',
      },
      buttonTransition: {
        from: 'from-red-100',
        to: 'to-red-300',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'bg-gradient-to-tr',
        hoverFrom: 'from-red-200',
        hoverTo: 'to-red-400',
        text: 'text-red-900',
      },
    },
  },
  emerald: {
    name: 'Emerald',
    bg: {
      main: 'bg-green-900',
      header: 'bg-green-800',
      primary: 'bg-yellow-300',
      card: 'bg-green-700',
      panel: 'bg-green-700',
      progress: 'bg-green-800',
    },
    text: {
      main: 'text-green-50',
      primary: 'text-yellow-300',
      subText: 'text-green-200',
      link: 'text-green-100',
      hoverPrimary: 'hover:text-yellow-300',
    },
    borders: {
      primary: 'border-yellow-300',
      text: 'border-green-50',
      card: 'border-green-700',
      skeleton: 'border-yellow-100',
      hoverPrimary: 'hover:border-yellow-300',
      focusPrimary: 'focus:border-yellow-300',
    },
    rings: {
      bg: 'ring-green-900',
      header: 'ring-green-800',
      primary: 'ring-yellow-300',
      focusPrimary: 'focus:ring-yellow-300',
    },
    skeletons: {
      main: 'bg-green-500',
      second: 'bg-green-800',
    },
    buttons: {
      primary: {
        bg: 'bg-yellow-300',
        text: 'text-yellow-900',
        hoverBg: 'hover:bg-yellow-400',
        hoverText: 'hover:text-yellow-900',
        focusBg: 'focus:bg-yellow-400',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-green-50',
        border: 'text-green-50',
        hoverBg: 'hover:bg-green-50',
        hoverText: 'hover:text-green-900',
        focusBg: 'focus:bg-green-50',
        focusText: 'focus:text-green-900',
      },
      self: {
        bg: 'bg-green-500',
        text: 'text-green-50',
        hoverBg: 'hover:bg-green-600',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-green-600',
      placeholder: 'placeholder-green-50',
    },
    gradients: {
      main: {
        from: 'from-yellow-300',
        to: 'to-yellow-100',
        direction: 'bg-gradient-to-tr',
        text: 'text-yellow-900',
      },
      bg: {
        from: 'from-green-300',
        to: 'to-green-600',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-green-900',
        to: 'bg-transparent',
      },
      button: {
        from: 'from-yellow-400',
        to: 'to-yellow-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'hover:bg-gradient-to-tr',
        hoverFrom: 'hover:from-yellow-500',
        hoverTo: 'hover:to-yellow-200',
        text: 'text-yellow-900',
      },
      buttonTransition: {
        from: 'from-yellow-400',
        to: 'to-yellow-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'bg-gradient-to-tr',
        hoverFrom: 'from-yellow-500',
        hoverTo: 'to-yellow-200',
        text: 'text-yellow-900',
      },
    },
  },
  violet: {
    name: 'Violet',
    bg: {
      main: 'bg-violet-900',
      header: 'bg-violet-800',
      primary: 'bg-teal-600',
      card: 'bg-violet-600',
      panel: 'bg-violet-600',
      progress: 'bg-violet-800',
    },
    text: {
      main: 'text-violet-50',
      primary: 'text-teal-600',
      subText: 'text-violet-200',
      link: 'text-violet-100',
      hoverPrimary: 'hover:text-teal-600',
    },
    borders: {
      primary: 'border-teal-600',
      text: 'border-violet-50',
      card: 'border-violet-600',
      skeleton: 'border-teal-100',
      hoverPrimary: 'hover:border-teal-600',
      focusPrimary: 'focus:border-teal-600',
    },
    rings: {
      bg: 'ring-violet-900',
      header: 'ring-violet-800',
      primary: 'ring-teal-600',
      focusPrimary: 'focus:ring-teal-600',
    },
    skeletons: {
      main: 'bg-violet-500',
      second: 'bg-violet-800',
    },
    buttons: {
      primary: {
        bg: 'bg-teal-400',
        text: 'text-teal-900',
        hoverBg: 'hover:bg-teal-500',
        hoverText: 'hover:text-teal-900',
        focusBg: 'focus:bg-teal-500',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-violet-50',
        border: 'text-violet-50',
        hoverBg: 'hover:bg-violet-50',
        hoverText: 'hover:text-violet-900',
        focusBg: 'focus:bg-violet-50',
        focusText: 'focus:text-violet-900',
      },
      self: {
        bg: 'bg-violet-500',
        text: 'text-violet-50',
        hoverBg: 'hover:bg-violet-600',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-violet-700',
      placeholder: 'placeholder-violet-100',
    },
    gradients: {
      main: {
        from: 'from-teal-300',
        to: 'to-teal-100',
        direction: 'bg-gradient-to-tr',
        text: 'text-teal-900',
      },
      bg: {
        from: 'from-violet-200',
        to: 'to-violet-500',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-violet-900',
        to: 'bg-transparent',
      },
      button: {
        from: 'from-teal-500',
        to: 'to-teal-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'hover:bg-gradient-to-tr',
        hoverFrom: 'hover:from-teal-600',
        hoverTo: 'hover:to-teal-200',
        text: 'text-teal-900',
      },
      buttonTransition: {
        from: 'from-teal-500',
        to: 'to-teal-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'bg-gradient-to-tr',
        hoverFrom: 'from-teal-600',
        hoverTo: 'to-teal-200',
        text: 'text-teal-900',
      },
    },
  },
  teal: {
    name: 'Teal',
    bg: {
      main: 'bg-teal-800',
      header: 'bg-teal-700',
      primary: 'bg-pink-300',
      card: 'bg-teal-600',
      panel: 'bg-teal-600',
      progress: 'bg-teal-700',
    },
    text: {
      main: 'text-teal-50',
      primary: 'text-pink-300',
      subText: 'text-teal-200',
      link: 'text-teal-100',
      hoverPrimary: 'hover:text-pink-300',
    },
    borders: {
      primary: 'border-pink-300',
      text: 'border-teal-50',
      card: 'border-teal-600',
      skeleton: 'border-pink-100',
      hoverPrimary: 'hover:border-pink-300',
      focusPrimary: 'focus:border-pink-300',
    },
    rings: {
      bg: 'ring-teal-800',
      header: 'ring-teal-700',
      primary: 'ring-pink-300',
      focusPrimary: 'focus:ring-pink-300',
    },
    skeletons: {
      main: 'bg-teal-500',
      second: 'bg-teal-700',
    },
    buttons: {
      primary: {
        bg: 'bg-pink-300',
        text: 'text-pink-900',
        hoverBg: 'hover:bg-pink-400',
        hoverText: 'hover:text-pink-900',
        focusBg: 'focus:bg-pink-400',
      },
      ghost: {
        bg: 'bg-transparent',
        text: 'text-teal-50',
        border: 'text-teal-50',
        hoverBg: 'hover:bg-teal-50',
        hoverText: 'hover:text-teal-800',
        focusBg: 'focus:bg-teal-50',
        focusText: 'focus:text-teal-800',
      },
      self: {
        bg: 'bg-teal-500',
        text: 'text-teal-50',
        hoverBg: 'hover:bg-teal-600',
      },
      default: {
        bg: 'bg-gray-100',
        text: 'text-gray-900',
        hoverBg: 'hover:bg-gray-200',
        focusBg: 'focus:bg-gray-200',
      },
    },
    input: {
      bg: 'bg-teal-700',
      placeholder: 'placeholder-teal-100',
    },
    gradients: {
      main: {
        from: 'from-pink-300',
        to: 'to-pink-100',
        direction: 'bg-gradient-to-tr',
        text: 'text-pink-900',
      },
      bg: {
        from: 'from-teal-300',
        to: 'to-teal-500',
        direction: 'bg-gradient-to-tl',
      },
      bgFade: {
        from: 'from-teal-800',
        to: 'to-transparent',
      },
      button: {
        from: 'from-pink-300',
        to: 'to-pink-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'hover:bg-gradient-to-tr',
        hoverFrom: 'hover:from-pink-400',
        hoverTo: 'hover:to-pink-300',
        text: 'text-pink-900',
      },
      buttonTransition: {
        from: 'from-pink-300',
        to: 'to-pink-100',
        direction: 'bg-gradient-to-tl',
        hoverDirection: 'bg-gradient-to-tr',
        hoverFrom: 'from-pink-400',
        hoverTo: 'to-pink-300',
        text: 'text-pink-900',
      },
    },
  },
}

export default themeOptions
